opensearch:
  serviceType: ClusterIP
  security:
    enabled: true
    linkerd:
      enabled: true
    volumeMounts:
      - name: certs
        mountPath: "/usr/share/opensearch/config/node.pem"
        subPath: node.pem
      - name: certs
        mountPath: "/usr/share/opensearch/config/node-key.pem"
        subPath: node-key.pem
      - name: certs
        mountPath: "/usr/share/opensearch/config/root-ca.pem"
        subPath: root-ca.pem
      - name: certs
        mountPath: "/usr/share/opensearch/config/admin.pem"
        subPath: admin.pem
      - name: certs
        mountPath: "/usr/share/opensearch/config/admin-key.pem"
        subPath: admin-key.pem
      - name: config
        mountPath: /usr/share/opensearch/config/opensearch.yml
        subPath: opensearch.yml
      - name: config
        mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
        subPath: internal_users.yml
      - name: config
        mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
        subPath: config.yml
      - name: config
        mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
        subPath: roles.yml
      - name: config
        mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
        subPath: roles_mapping.yml
  env:
    cluster.name: "milkyway"
    http.compression: "true"
    network.host: "0.0.0.0"
    cluster.routing.allocation.disk.threshold_enabled: "false"
  image:
    repository: ghcr.io/navikt/pam-opensearch
    tag: 1.0.1
    pullPolicy: IfNotPresent
  stateful:
    class: "hostpath"

master:
  replicas: 3
  antiAffinity: "soft"
  resources:
    requests:
      memory: 256Mi
  env:
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    node.master: true
    node.data: false
    node.ingest: false
  stateful:
    size: 1Gi

ingest:
  replicas: 2
  antiAffinity: "soft"
  heapMemory: 256m
  resources:
    requests:
      memory: 256Mi
  env:
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    node.master: false
    node.data: false
    node.ingest: true
data:
  replicas: 3
  antiAffinity: "soft"
  heapMemory: 256m
  resources:
    requests:
      memory: 256Mi
  env:
    ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    node.master: false
    node.data: true
    node.ingest: false
  stateful:
    size: 4Gi

ingress:
  domain: localhost
  class: gw-localhost

