{{ if and .Values.opensearch.security.enabled .Values.opensearch.security.linkerd.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: nais
        podSelector:
          matchLabels:
            app: prometheus
    - from:
      - namespaceSelector:
          matchLabels:
            linkerd.io/is-control-plane: "true"
    - from:
      - namespaceSelector:
          matchLabels:
            linkerd.io/extension: viz
        podSelector:
          matchLabels:
            component: tap
    - from:
      - namespaceSelector:
          matchLabels:
            linkerd.io/extension: viz
        podSelector:
          matchLabels:
            component: prometheus
    - from:
      - namespaceSelector:
          matchLabels:
            name: nginx
        podSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Values.ingress.domain }}
      - namespaceSelector:
          matchLabels:
            name: teampam
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            linkerd.io/is-control-plane: "true"
      - namespaceSelector:
          matchLabels:
            name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      - namespaceSelector:
          matchLabels:
            name: teampam
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
            - 10.6.0.0/15
            - 172.16.0.0/12
            - 192.168.0.0/16
{{ end }}
