apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-certs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
type: Opaque
stringData:
  node.pem: |-
{{ .Files.Get (printf ".secrets/%s/node.pem" .Values.env.cluster) | indent 4 }}
  node-key.pem: |-
{{ .Files.Get (printf ".secrets/%s/node-key.pem" .Values.env.cluster) | indent 4 }}
  root-ca.pem: |-
{{ .Files.Get (printf ".secrets/%s/root-ca.pem" .Values.env.cluster) | indent 4 }}
  admin.pem: |-
{{ .Files.Get (printf ".secrets/%s/admin.pem" .Values.env.cluster) | indent 4 }}
  admin-key.pem: |-
{{ .Files.Get (printf ".secrets/%s/admin-key.pem" .Values.env.cluster) | indent 4 }}

